config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

import users.views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", users.views.register, name="register"),
    path("", include("litrevu.urls")),
    path("", include("reviews.urls")),
    path("", include("tickets.urls")),
    path("", include("users.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        # ...
    ] + urlpatterns

litrevu/urls.py
from django.urls import path

from litrevu.views import feed, landing_page

urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("feed/", feed, name="feed"),
]

users/urls.py
from django.urls import path

from users.views import social_view, unblock_view, unfollow_view

urlpatterns = [
    path("subscriptions/", social_view, name="subscriptions"),
    path("unfollow/<int:user_id>/", unfollow_view, name="unfollow_view"),
    path("unblock/<int:user_id>/", unblock_view, name="unblock_view"),
]

litrevu/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    time_created = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128)
    body = models.TextField(max_length=8192, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name="following",
    )
    followed_user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name="followed_by",
    )

    class Meta:
        unique_together = (
            "user",
            "followed_user",
        )
        verbose_name = "User Follows"
        verbose_name_plural = "User Follows"


class UserBlocked(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name="blocking",
    )
    blocked_user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name="blocked_by",
    )

    class Meta:
        unique_together = (
            "user",
            "blocked_user",
        )
        verbose_name = "User blocks"
        verbose_name_plural = "User Blocks"

litrevu/views.py
from itertools import chain

from django.contrib.auth.decorators import login_required
from django.db.models import CharField, Exists, F, OuterRef, Q, Subquery, Value
from django.db.models.functions import Concat
from django.shortcuts import render

from config import settings
from reviews.models import Review
from tickets.models import Ticket
from users.models import UserBlocked, UserFollows

ID = int


def landing_page(request):
    return render(request, "landing_page.html")


@login_required
def feed(request):
    followed_user_ids = UserFollows.objects.filter(user=request.user).values_list(
        "followed_user", flat=True
    )

    user_tickets_subquery = Ticket.objects.filter(user=request.user).values_list(
        "id", flat=True
    )

    user_tickets = Ticket.objects.filter(
        id__in=Subquery(user_tickets_subquery)
    ).annotate(
        content_type=Value("TICKET", CharField()),
        username=F("user__username"),
        has_review=Exists(Review.objects.filter(ticket_id=OuterRef("id"))),
        is_editable=Value(True),
    )

    # Tickets from current user or followed users
    followed_users_tickets = Ticket.objects.filter(
        user_id__in=Subquery(followed_user_ids)
    ).annotate(
        content_type=Value("TICKET", CharField()),
        username=F("user__username"),
        has_review=Exists(Review.objects.filter(ticket_id=OuterRef("id"))),
        is_editable=Value(False),
    )

    # Reviews by current user
    user_reviews = Review.objects.filter(user=request.user).annotate(
        content_type=Value("USER_REVIEW", CharField()),
        ticket_title=F("ticket__title"),
        ticket_description=F("ticket__description"),
        ticket_username=F("ticket__user__username"),
        ticket_image_url=Concat(
            Value(settings.MEDIA_URL), F("ticket__image"), output_field=CharField()
        ),
        ticket_time_created=F("ticket__time_created"),
        review_username=F("user__username"),
        is_editable=Value(True),
    )

    blocked_users_subquery = UserBlocked.objects.filter(user=request.user).values_list(
        "blocked_user_id", flat=True
    )

    # Reviews by followed users or by followers
    reviews = (
        Review.objects.filter(
            Q(user_id__in=Subquery(followed_user_ids))
            | Q(ticket_id__in=Subquery(user_tickets_subquery))
        )
        .exclude(user_id__in=Subquery(blocked_users_subquery))
        .annotate(
            content_type=Value("REVIEW", CharField()),
            ticket_title=F("ticket__title"),
            ticket_username=F("ticket__user__username"),
            review_username=F("user__username"),
            is_editable=Value(False),
        )
    )

    posts = sorted(
        chain(reviews, user_tickets, followed_users_tickets, user_reviews),
        key=lambda post: post.time_created,
        reverse=True,
    )

    return render(request, "feed.html", context={"posts": posts})

litrevu/templates/create_review.html
{% extends "base/base.html" %}
{% block content %}

<div class="max-w-2xl mx-auto bg-white rounded-lg border border-gray-200 shadow-md overflow-hidden my-4 p-5">
    <style>
        .rating {
            display: inline-flex;
            flex-direction: row-reverse;
            justify-content: flex-end;
        }

        .star {
            cursor: pointer;
            font-size: 2rem;
            color: lightgray;
        }

        input[type="radio"]:checked ~ .star {
            color: orange;
        }
    </style>
    <h2 class="text-lg font-medium text-gray-700 mt-3">You are posting a review for: {{ ticket.title }}</h2>
    <p class="text-gray-600 mt-2">{{ ticket.description }}</p>

    {% if ticket.image %}
    <div class="flex justify-center">
        <img src="{{ ticket.image.url }}" alt="{{ ticket.title }}" class="mt-4 w-1/2 object-cover rounded-lg">
    </div>

    {% endif %}

    <form method="post" class="space-y-4 mt-6">
        {% csrf_token %}
        <h3 class="text-lg font-medium text-gray-700">Create a Review for {{ ticket.title }}</h3>
        <div class="rating">
            {% for value in "54321" %}
            <input type="radio" id="star{{ value }}" name="rating" value="{{ value }}" class="hidden"/>
            <label for="star{{ value }}" class="star">&#9733;</label>
            {% endfor %}
        </div>

        <div>
            <label for="headline" class="block text-sm font-medium text-gray-700">Headline</label>
            <textarea name="headline" id="headline"
                      class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
        </div>
        <div>
            <label for="body" class="block text-sm font-medium text-gray-700">Comment</label>
            <textarea name="body" id="body"
                      class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
        </div>
        <button type="submit"
                class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
            Submit Review
        </button>
    </form>
</div>


{% endblock %}

litrevu/templates/create_ticket.html
{% extends "base/base.html" %}
{% block content %}
<div class="max-w-md mx-auto bg-white rounded-lg border border-gray-200 shadow-md overflow-hidden md:max-w-2xl my-4 p-5">
    <h2 class="block mt-1 text-lg leading-tight font-medium text-black">New ticket</h2>
    <form method="post" enctype="multipart/form-data" class="space-y-4">
        {% csrf_token %}
        <div>
            <label for="id_title" class="block text-sm font-medium text-gray-700">Title</label>
            <input type="text" name="title" id="id_title"
                   class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
        </div>
        <div>
            <label for="id_description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea name="description" id="id_description"
                      class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
        </div>
        <div>
            <label for="id_image" class="block text-sm font-medium text-gray-700">Image</label>
            <input type="file" name="image" id="id_image"
                   class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
        </div>
        <button type="submit"
                class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
            Submit ticket
        </button>
    </form>
</div>
{% endblock %}

litrevu/templates/create_ticket_and_review.html
{% extends "base/base.html" %}

{% block content %}
<style>
    .rating {
        display: inline-flex;
        flex-direction: row-reverse;
        justify-content: flex-end;
    }

    .star {
        cursor: pointer;
        font-size: 2rem;
        color: lightgray;
    }

    input[type="radio"]:checked ~ .star {
        color: orange;
    }
</style>
<div class="max-w-2xl mx-auto bg-white rounded-lg border border-gray-200 shadow-md overflow-hidden my-4 p-5">
    <h1 class="block mt-1 text-lg leading-tight font-medium text-black">New ticket and review</h1>
    <form method="post" enctype="multipart/form-data" class="space-y-4">
        {% csrf_token %}
        <h3 class="text-lg font-medium text-gray-700">Ticket</h3>
        <div>
            <label for="id_title" class="block text-sm font-medium text-gray-700">Title</label>
            <input type="text" name="title" id="id_title"
                   class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
        </div>
        <div>
            <label for="id_description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea name="description" id="id_description"
                      class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
        </div>
        <div>
            <label for="id_image" class="block text-sm font-medium text-gray-700">Image</label>
            <input type="file" name="image" id="id_image"
                   class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
        </div>

        <h3 class="text-lg font-medium text-gray-700 mt-6">Review</h3>
        <div>
            <span class="block text-sm font-medium text-gray-700">Rating</span>
            <div class="rating">
                {% for value in "54321" %}
                <input type="radio" id="star{{ value }}" name="rating" value="{{ value }}" class="hidden"/>
                <label for="star{{ value }}" class="star">&#9733;</label>
                {% endfor %}
            </div>
        </div>
        <div>
            <label for="id_headline" class="block text-sm font-medium text-gray-700">Headline</label>
            <input type="text" name="headline" id="id_headline"
                   class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
        </div>
        <div>
            <label for="id_body" class="block text-sm font-medium text-gray-700">Body</label>
            <textarea name="body" id="id_body"
                      class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
        </div>

        <button type="submit"
                class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-900 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
            Submit ticket & review
        </button>
    </form>
</div>
{% endblock %}

litrevu/templates/edit_review.html
{% extends "base/base.html" %}
{% block content %}

<div class="max-w-2xl mx-auto bg-white rounded-lg border border-gray-200 shadow-md overflow-hidden my-4 p-5">
    <style>
        .rating {
            display: inline-flex;
            flex-direction: row-reverse;
            justify-content: flex-end;
        }

        .star {
            cursor: pointer;
            font-size: 2rem;
            color: lightgray;
        }

        input[type="radio"]:checked ~ .star {
            color: orange;
        }
    </style>
    <h2 class="text-lg font-medium text-gray-700 mt-3">You are posting a review for: {{ ticket.title }}</h2>
    <p class="text-gray-600 mt-2">{{ ticket.description }}</p>

    {% if ticket.image %}
    <div class="flex justify-center">
        <img src="{{ ticket.image.url }}" alt="{{ ticket.title }}" class="mt-4 w-1/2 object-cover rounded-lg">
    </div>

    {% endif %}

    <form method="post" class="space-y-4 mt-6">
        {% csrf_token %}
        <h3 class="text-lg font-medium text-gray-700">Create a Review for {{ ticket.title }}</h3>
        <div class="rating">
            {% for value in "54321" %}
            <input type="radio" id="star{{ value }}" name="rating" value="{{ value }}" class="hidden"/>
            <label for="star{{ value }}" class="star">&#9733;</label>
            {% endfor %}
        </div>

        <div>
            <label for="headline" class="block text-sm font-medium text-gray-700">Headline</label>
            <textarea name="headline" id="headline"
                      class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
        </div>
        <div>
            <label for="body" class="block text-sm font-medium text-gray-700">Comment</label>
            <textarea name="body" id="body"
                      class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
        </div>
        <button type="submit"
                class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-900 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
            Submit Review
        </button>
    </form>
</div>


{% endblock %}

litrevu/templates/edit_ticket.html
{% extends "base/base.html" %}
{% block content %}
<div class="max-w-md mx-auto bg-white rounded-lg border border-gray-200 shadow-md overflow-hidden md:max-w-2xl my-4 p-5">
    <h2 class="block mt-1 text-lg leading-tight font-medium text-black">Ticket</h2>
    <form method="post" enctype="multipart/form-data" class="space-y-4">
        {% csrf_token %}
        <div>
            <label for="id_title" class="block text-sm font-medium text-gray-700">Title</label>
            <input type="text" name="title" id="id_title"
                   class="mt-1 focus:ring-sky-900 focus:border-sky-900 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
        </div>
        <div>
            <label for="id_description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea name="description" id="id_description"
                      class="mt-1 focus:ring-sky-900 focus:border-sky-900 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"></textarea>
        </div>
        <div>
            <label for="id_image" class="block text-sm font-medium text-gray-700">Image</label>
            <input type="file" name="image" id="id_image"
                   class="mt-1 focus:ring-sky-900 focus:border-sky-900 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
        </div>
        <button type="submit"
                class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-900 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-900">
            Submit ticket
        </button>
    </form>
</div>
{% endblock %}

litrevu/templates/feed.html
{% extends 'base/base.html' %}
{% block content %}
<div class="text-center mb-8">
    <div class="inline-block mx-auto max-w-md">
        <div class="flex justify-between space-x-24">
            <a class="inline-flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-900 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500" href="{% url 'create_ticket' %}">Ask for a review</a>
            <a class="inline-flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-900 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500" href="{% url 'create_ticket_and_review' %}">Create a review</a>
        </div>
    </div>
</div>
{% for post in posts %}
  <div class="my-4">
    {% if post.content_type == 'TICKET' %}
      {% with ticket=post %}
        {% include './components/ticket.html' %}
      {% endwith %}
    {% elif post.content_type == 'USER_REVIEW' %}
      {% with ticket_and_review=post %}
        {% include './components/user_review.html' %}
      {% endwith %}
    {% elif post.content_type == 'REVIEW' %}
      {% with review=post %}
        {% include './components/review.html' %}
      {% endwith %}
    {% endif %}
  </div>
{% endfor %}
{% endblock %}

litrevu/templates/follow_view.html
{% extends "base/base.html" %}
{% block content %}
<div class="max-w-2xl mx-auto p-5">
    {% if messages %}
    {% endif %}
    <h2 class="text-2xl font-semibold text-gray-800">Users</h2>
    <form method="post" class="mt-4 bg-white rounded-lg border border-gray-200 shadow-md p-4">
        {% csrf_token %}
        <div class="mb-4">
            <label for="user_to_act_on" class="block text-sm font-medium text-gray-700">Username</label>
            <input type="text" id="user_to_act_on" name="user_to_act_on"
                   class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">

            <fieldset class="mt-4">
                <legend class="text-sm font-medium text-gray-700">{{ form.action.label }}</legend>
                <div class="mt-2 flex items-center space-x-6">
                    <div class="flex items-center">
                        <input id="follow" name="action" type="radio" value="follow"
                               class="focus:ring-sky-500 h-4 w-4 text-sky-600 border-gray-300" checked>
                        <label for="follow" class="ml-2 block text-sm font-medium text-gray-700">
                            Follow
                        </label>
                    </div>
                    <div class="flex items-center">
                        <input id="block" name="action" type="radio" value="block"
                               class="focus:ring-red-500 h-4 w-4 text-red-600 border-gray-300">
                        <label for="block" class="ml-2 block text-sm font-medium text-gray-700">
                            Block
                        </label>
                    </div>
                </div>
            </fieldset>
        </div>
        <button type="submit"
                class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-900 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
            Submit
        </button>
    </form>

    <div class="md:grid md:grid-cols-2 md:gap-6 mt-8">

        <div class="bg-gray-200 p-4 rounded-lg">

            <div>
                <h2 class="text-xl text-center font-semibold text-gray-800">Following</h2>
                <ul class="list-disc list-inside">
                    {% for follow in following %}
                    <li class="flex justify-between items-center bg-white rounded-lg border border-gray-200 shadow-md p-4 my-2">
                        {{ follow.followed_user.username }}
                        <form method="post" action="{% url 'unfollow_view' follow.followed_user.id %}" class="ml-4">
                            {% csrf_token %}
                            <button type="submit"
                                    class="py-1 px-3 bg-red-900 hover:bg-red-600 text-white font-bold rounded-lg">
                                Unfollow
                            </button>
                        </form>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <h2 class="text-xl text-center font-semibold text-gray-800 mt-8">Followed by</h2>
            <ul class="list-disc list-inside">
                {% for follow in followers %}
                <li class="bg-white rounded-lg border border-gray-200 shadow-md p-4 my-2">{{ follow.user.username }}
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="bg-gray-200 p-4 rounded-lg">
            <h2 class="text-xl text-center font-semibold text-gray-800">Blocked</h2>
            <ul class="list-disc list-inside">
                {% for block in blocked %}
                {% with blocked_user=block.blocked_user %}
                <li class="bg-white rounded-lg border border-gray-200 shadow-md p-4 my-2 flex justify-between items-center">
                    {{ blocked_user.username }}
                    <form method="post" action="{% url 'unblock_view' blocked_user.id %}">
                        {% csrf_token %}
                        <button type="submit"
                                class="py-1 px-3 bg-sky-500 hover:bg-sky-600 text-white font-bold rounded-lg">
                            Unblock
                        </button>
                    </form>
                </li>
                {% endwith %}
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

litrevu/templates/landing_page.html
{% extends "base/base.html" %}

{% block content %}


{% if user.is_authenticated %}
    <h1>Welcome, {{ user.username }}!</h1>
    <a href="{% url 'feed' %}">Go to Your feed</a>
{% else %}

<div class="flex justify-between items-stretch mx-auto">

    <div class="flex-1 p-8">
        <h2 class="text-lg font-semibold text-gray-800">Register now</h2>
        <a href="{% url 'register' %}"
           class="mt-3 inline-flex items-center py-2 px-4 text-sm font-medium text-center text-white bg-sky-600 rounded-lg hover:bg-sky-700 focus:ring-4 focus:ring-sky-300">
            Register
        </a>
    </div>


    <div class="flex-1 p-8">
        <h2 class="text-lg font-semibold text-gray-800">Connect</h2>
        <form method="post" action="{% url 'login' %}" class="mt-4 space-y-4">
            {% csrf_token %}
            <div>
                <label for="id_username_login" class="block text-sm font-medium text-gray-700">Username</label>
                <input type="text" name="username" id="id_username_login"
                       class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
            </div>
            <div>
                <label for="id_password_login" class="block text-sm font-medium text-gray-700">Password</label>
                <input type="password" name="password" id="id_password_login"
                       class="mt-1 focus:ring-sky-500 focus:border-sky-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
            </div>
            <button type="submit"
                    class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-sky-600 hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                Login
            </button>
        </form>
    </div>

</div>


{% endif %}
{% endblock %}